- type: department
  id: ColonialCommand
  name: department-ColonialCommand
  description: department-ColonialCommand-description
  color: "#1C4D8D"
  roles:
  - ColonialCommandOfficial
  - CAFLeader
  - CAFTrooper
  - CAFEngineer
  - CAFMedical
  editorHidden: true
  weight: 120
